// <auto-generated />
using MegaFpCSharpTodoBackEndTotallyNotButtCheeks.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MegaFpCSharpTodoBackEndTotallyNotButtCheeks.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20190328140255_StrongKeys")]
    partial class StrongKeys
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MegaFpCSharpTodoBackEndTotallyNotButtCheeks.Data.Todo", b =>
                {
                    b.Property<int>("TodoId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<bool>("IsActive");

                    b.HasKey("TodoId");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            TodoId = 1,
                            Description = "dummy",
                            IsActive = true
                        },
                        new
                        {
                            TodoId = 2,
                            Description = "another dummy",
                            IsActive = true
                        },
                        new
                        {
                            TodoId = 3,
                            Description = "A third dummy",
                            IsActive = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
